export type AnnouncementType =
| 'UNIVERSITY_ANNOUNCEMENT'
| 'UNIVERSITY_GUEST_ANNOUNCEMENT'
| 'COLLEGE_ANNOUNCEMENT'
| 'COLLEGE_GUEST_ANNOUNCEMENT'
| 'SUBJECT_ANNOUNCEMENT'
| 'SUBJECT_EXAM_RESULT_ANNOUNCEMENT'
| 'SUBJECT_EXAM_DATE_ANNOUNCEMENT'
| 'INTERNSHIP_ANNOUNCEMENT'
| 'ACTIVITIES_ANNOUNCEMENT';